# Generated by Django 5.1 on 2024-08-24 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diretor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField()),
                ("nacionalidade", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("ano_lancamento", models.IntegerField()),
                ("genero", models.CharField(max_length=50)),
                ("sinopse", models.TextField(blank=True, null=True)),
                ("informacoes_adicionais", models.JSONField(blank=True, null=True)),
                (
                    "diretor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="persons.diretor",
                    ),
                ),
            ],
        ),
    ]
